services:
  - type: web
    name: docmind-backend
    runtime: docker
    rootDir: backend
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: ai_doc_qa
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: docmind-frontend
    runtime: docker
    rootDir: frontend
    envVars:
      - key: REACT_APP_API_URL
        sync: false
